# Generated by Django 4.1.4 on 2023-04-04 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('dni', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('1', 'ACTIVO'), ('2', 'INACTIVO'), ('3', 'BLOQUEADO')], max_length=10)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('broadcast_date', models.DateField()),
                ('link', models.CharField(max_length=150)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_guide.guide')),
            ],
        ),
    ]
