# Generated by Django 4.1.4 on 2023-04-04 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour_guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calification', models.FloatField()),
                ('comment', models.TextField()),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_guide.guide')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
