# Generated by Django 4.1.3 on 2023-04-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='id_user',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='favorite_site',
            name='id_user',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='guide_site',
            name='dni',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='visit_site',
            name='id_user',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
