# Generated by Django 4.1.4 on 2023-04-13 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourist_spot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('id_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist_spot.site')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
